apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: telecom
      defaultBucket: telecom_metrics
    secureJsonData:
      token: telecom-super-secret-auth-token-2026
